"""Custom Fields for ERPNext DocTypes — EV Workshop.

This fixture defines custom fields added to standard ERPNext doctypes.
These fields are created when the app is installed via `bench migrate`.

Fields added:
    On Item doctype:
        - ev_workshop_section: Section Break (collapsible)
        - ev_item_class: Select (Spare Part / Service / Consumable)
        - ev_hsn_code: Data (HSN code for GST)
        - ev_sgst_percent: Percent
        - ev_cgst_percent: Percent
        - ev_igst_percent: Percent

    On Sales Invoice doctype:
        - job_reference: Link to Job Master

These fields allow ERPNext's standard Item and Sales Invoice doctypes
to carry EV Workshop-specific data without overriding the doctypes.
"""

def get_custom_fields():
    return [
        {
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 1,
            "collapsible_depends_on": None,
            "columns": 0,
            "creation": "2026-03-07 08:00:00.000000",
            "default": None,
            "depends_on": None,
            "description": None,
            "docstatus": 0,
            "dt": "Item",
            "fetch_from": None,
            "fetch_if_empty": 0,
            "fieldname": "ev_workshop_section",
            "fieldtype": "Section Break",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "idx": 1,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "item_tax_section_break",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "EV Workshop",
            "length": 0,
            "mandatory_depends_on": None,
            "modified": "2026-03-07 08:00:00.000000",
            "modified_by": "Administrator",
            "module": "EV Workshop",
            "name": "Item-ev_workshop_section",
            "no_copy": 0,
            "non_negative": 0,
            "options": "fa fa-wrench",
            "owner": "Administrator",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "read_only": 0,
            "read_only_depends_on": None,
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "show_dashboard": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": None
        },
        {
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": None,
            "columns": 0,
            "creation": "2026-03-07 08:01:00.000000",
            "default": None,
            "depends_on": None,
            "description": "Classification for EV Workshop items",
            "docstatus": 0,
            "dt": "Item",
            "fetch_from": None,
            "fetch_if_empty": 0,
            "fieldname": "ev_item_class",
            "fieldtype": "Select",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "idx": 2,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "ev_workshop_section",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Item Class",
            "length": 0,
            "mandatory_depends_on": None,
            "modified": "2026-03-07 08:01:00.000000",
            "modified_by": "Administrator",
            "module": "EV Workshop",
            "name": "Item-ev_item_class",
            "no_copy": 0,
            "non_negative": 0,
            "options": "Spare Part\nService\nConsumable",
            "owner": "Administrator",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "read_only": 0,
            "read_only_depends_on": None,
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "show_dashboard": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": None
        },
        {
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": None,
            "columns": 0,
            "creation": "2026-03-07 08:02:00.000000",
            "default": None,
            "depends_on": None,
            "description": "HSN Code for GST purposes",
            "docstatus": 0,
            "dt": "Item",
            "fetch_from": None,
            "fetch_if_empty": 0,
            "fieldname": "ev_hsn_code",
            "fieldtype": "Data",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "idx": 3,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "ev_item_class",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "HSN Code",
            "length": 0,
            "mandatory_depends_on": None,
            "modified": "2026-03-07 08:02:00.000000",
            "modified_by": "Administrator",
            "module": "EV Workshop",
            "name": "Item-ev_hsn_code",
            "no_copy": 0,
            "non_negative": 0,
            "options": None,
            "owner": "Administrator",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "read_only": 0,
            "read_only_depends_on": None,
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "show_dashboard": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": None
        },
        {
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": None,
            "columns": 0,
            "creation": "2026-03-07 08:03:00.000000",
            "default": None,
            "depends_on": None,
            "description": None,
            "docstatus": 0,
            "dt": "Item",
            "fetch_from": None,
            "fetch_if_empty": 0,
            "fieldname": "ev_tax_section",
            "fieldtype": "Column Break",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "idx": 4,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "ev_hsn_code",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "EV Tax Details",
            "length": 0,
            "mandatory_depends_on": None,
            "modified": "2026-03-07 08:03:00.000000",
            "modified_by": "Administrator",
            "module": "EV Workshop",
            "name": "Item-ev_tax_section",
            "no_copy": 0,
            "non_negative": 0,
            "options": None,
            "owner": "Administrator",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "read_only": 0,
            "read_only_depends_on": None,
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "show_dashboard": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": None
        },
        {
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": None,
            "columns": 0,
            "creation": "2026-03-07 08:04:00.000000",
            "default": "0",
            "depends_on": None,
            "description": None,
            "docstatus": 0,
            "dt": "Item",
            "fetch_from": None,
            "fetch_if_empty": 0,
            "fieldname": "ev_sgst_percent",
            "fieldtype": "Percent",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "idx": 5,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "ev_tax_section",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "SGST (%)",
            "length": 0,
            "mandatory_depends_on": None,
            "modified": "2026-03-07 08:04:00.000000",
            "modified_by": "Administrator",
            "module": "EV Workshop",
            "name": "Item-ev_sgst_percent",
            "no_copy": 0,
            "non_negative": 0,
            "options": None,
            "owner": "Administrator",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "read_only": 0,
            "read_only_depends_on": None,
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "show_dashboard": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": None
        },
        {
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": None,
            "columns": 0,
            "creation": "2026-03-07 08:05:00.000000",
            "default": "0",
            "depends_on": None,
            "description": None,
            "docstatus": 0,
            "dt": "Item",
            "fetch_from": None,
            "fetch_if_empty": 0,
            "fieldname": "ev_cgst_percent",
            "fieldtype": "Percent",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "idx": 6,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "ev_sgst_percent",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "CGST (%)",
            "length": 0,
            "mandatory_depends_on": None,
            "modified": "2026-03-07 08:05:00.000000",
            "modified_by": "Administrator",
            "module": "EV Workshop",
            "name": "Item-ev_cgst_percent",
            "no_copy": 0,
            "non_negative": 0,
            "options": None,
            "owner": "Administrator",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "read_only": 0,
            "read_only_depends_on": None,
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "show_dashboard": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": None
        },
        {
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": None,
            "columns": 0,
            "creation": "2026-03-07 08:06:00.000000",
            "default": "0",
            "depends_on": None,
            "description": None,
            "docstatus": 0,
            "dt": "Item",
            "fetch_from": None,
            "fetch_if_empty": 0,
            "fieldname": "ev_igst_percent",
            "fieldtype": "Percent",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "idx": 7,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "ev_cgst_percent",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "IGST (%)",
            "length": 0,
            "mandatory_depends_on": None,
            "modified": "2026-03-07 08:06:00.000000",
            "modified_by": "Administrator",
            "module": "EV Workshop",
            "name": "Item-ev_igst_percent",
            "no_copy": 0,
            "non_negative": 0,
            "options": None,
            "owner": "Administrator",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "read_only": 0,
            "read_only_depends_on": None,
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "show_dashboard": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": None
        },
        {
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "creation": "2026-07-24 08:00:00.000000",
            "default": None,
            "depends_on": None,
            "description": "Link to EV Workshop Job Master",
            "docstatus": 0,
            "dt": "Sales Invoice",
            "fetch_from": None,
            "fetch_if_empty": 0,
            "fieldname": "job_reference",
            "fieldtype": "Link",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "idx": 1,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "naming_series",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Job Reference",
            "length": 0,
            "mandatory_depends_on": None,
            "modified": "2026-07-24 08:00:00.000000",
            "modified_by": "Administrator",
            "module": "EV Workshop",
            "name": "Sales Invoice-job_reference",
            "no_copy": 0,
            "non_negative": 0,
            "options": "Job Master",
            "owner": "Administrator",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "read_only": 0,
            "read_only_depends_on": None,
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "show_dashboard": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": None
        }
    ]
